### ISSUE TITLE
Facturette

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux-Pos#10]
L'édition d'une facturette se fait sur l'imprimante ticket (pas de choix) et est tronquée, je n'ai que la partie gauche de la facturette qui s'édite.

**Comment by Laurux** [comment]
Il faut aller dans les préférences et voir dans l'onglet environnement si le bouton facturette sur imprimante défaut est coché.

**Comment by PatrickMag** [comment]
Coché ou pas, j'ai le même résultat
L'imprimante par défaut est l'imprimante ticket, par contre l'imprimante A4 est installée sur un autre poste => Xerox ... @isilda-hp.local.
L'installer sur le poste en imprimante par défaut ?

**Comment by damscot** [comment]
perso j'utilise gtklp,
ainsi a chaque impression on fenetre s'ouvre et tu peux choisir sur quelle
imprimante tu envois ton impression.

**Comment by damscot** [comment]
patrick c'est bon pour toi? faut-il faire un fix je veux sortir la v3.25.1

**Comment by PatrickMag** [comment]
Oui c'est bon,  J'ai pas tout compris mais ça marche.Le 13 janv. 2018 11:51 PM, damscot <notifications@github.com> a écrit :patrick c'est bon pour toi? faut-il faire un fix je veux sortir la v3.25.1
