### ISSUE TITLE
commit 58374ee935d7f89f8448cd49fea4879c6f1ebf5a

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux-Pos#13]
@damscot dans le  commit : 58374ee935d7f89f8448cd49fea4879c6f1ebf5a
J'ai mis un "stop event" que tu a supprimé dans le suivant, y a t il une raison particulière ?
Le but de ce dernier était que lors de l'appui sur la touche tab le curseur n'avance pas de 2 positions.

**Comment by damscot** [comment]
c'est fixé il y avait eu un pb avec les articles générique (pvttc = 0) dans la fiche articles.
ca sera dans la v3.25.2
