### ISSUE TITLE
Plantage sur remise

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux-Pos#17]
Erreur remontée du forum : https://www.laurux.fr/drupal/node/305
Perso je n'arrive pas à la reproduire ...

**Comment by damscot** [comment]
pb vu sur laurux-pos 3.25.2, il n'est plus la sur master, probablement une correction déjà faite quand j'ai repris le travail sur les remises. Je clos, j'ai fait un commit sur Laurux pour renforcer la génération de facture qui plantait a cause de ce ticket mal formé... Il va falloir trouver une solution pour renforcer le moulinage, une société ne doit pas etre bloqué parceque un ticket est cassé.
