### ISSUE TITLE
Clients divers caisse

### ISSUE THREAD

**Issue by Laurux** [Laurux/Laurux-Pos#19]
le forum a été alimenté par une question concernant la mémorisation des clients de passage en caisse
https://www.laurux.fr/drupal/node/316
Cette fonction existait en caisse. Lors de l'impression d'une facturette, les coordonnées du client était mémorisée dans la table Fiches_Clid et pouvait être ensuite rappelée ensuite par F2 dans la fenêtre de saisie des coordonées du client.
Apparemment cette fonction a été supprimée lors du merge https://github.com/Laurux/Laurux-Pos/commit/d7578cd905ac4ed21a994b4efa9bf6d9de9c324a#diff-fa8bbeffd49ecd27b88a430d0b3255f6
Perso, je trouve ça dommage.

**Comment by damscot** [comment]
je vais remettre ca en place, cela a effectivement disparu lors des premiers merges ou la gestion git avait pêcher. comment la suppression/épuration des entrées était faites ?

**Comment by damscot** [comment]
j'ai l'impression qu'il y a eu d'autre modification, ca n'utilisait pas Fiches_Clid mais la table des cartes avec un enregistrement d''Origine" "divers", c'est bizzare comment c'était fait tu as plus de détail?

**Comment by Laurux** [comment]
Va falloir que je regarde sur d'anciennes sauvegardes.
Je ferai ça la semaine prochaine.

**Comment by damscot** [comment]
j'ai fait quelque chose avec la table Fiche_carte qui contient à la fois les clients cartes et les clients divers caisse, il est possible de supprimer des entrees depuis Laurux. l'enregistrement se fait a partir du moment ou l'option archivage des clients facturette est activé.
j'en ai profiter pour tester l'usage des bonus avec les clients cartes et cela n'a pas l'air de marcher et quand on valide le ticket, les infos du client carte reste visible a coté du montant du ticket... c'est un autre pb mais si tu as des infos comments marche les cartes de fidelité je suis preneur.
