### ISSUE TITLE
want integer, got null (coulfc)

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux-Pos#4]
Ligne caisse.225 
Apparemment c'est une variable setting pour gérer les couleurs mais je ne vois pas ou elle est initialisée dans le programme.

**Comment by damscot** [comment]
Mhhh... tu avais un fichier .conf existant ?
tu peux me le joindre?
j'ai essaye de reproduire en supprimant mon fichier de conf et je ne tombe pas dedans...

**Comment by damscot** [comment]
Fixed by 3b4bd8a41c38375b4afb4c9cb13e089d7478340e
