### ISSUE TITLE
Erreur TVA

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux-Pos#9]
Une erreur remontée du forum :
Bonsoir, lors du ticket Z je m'aperçois d'une erreur de calcul de tva:
HT 23.10
TVA 20.00 6.06
Total TTC 27.72
Le passage en compta est aussi faux mais pas avec d'autres chiffres:
HT 22.86
TVA 20.00 4.86
Pour info, Ticket avec remise globale.

**Comment by damscot** [comment]
Il serait interressant d'avoir plus de détail sur le ticket.
lignes, articles, familles et taux de tva impliqué.

Damien.

**Comment by PatrickMag** [comment]
@Laurux doit avoir plus de renseignements.

**Comment by damscot** [comment]
pas eu de news, je clos le ticket
